### ISSUE TITLE
Absence of both `vesting_terms_id` and `vestings` array means the shares are fully vested on issuance

### ISSUE THREAD

**Issue by jacobyavis** [Open-Cap-Table-Coalition/OCF-Tools#76]
A natural language rule mentioned in https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/pull/515

Opening an issue here to ensure this is tracked and the rule adhered to.

**Comment by MattCantor** [comment]
This has been implemented, commented in the code and referenced in the README.
