### ISSUE TITLE
If both `vestings` array and `vesting_terms_id` are present, defer to `vestings`

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/OCF-Tools#77]
natural language rule mentioned in https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/pull/515

Opening an issue here to ensure this is tracked and the rule adhered to.

**Comment by MattCantor** [comment]
This has been implemented in PR #118, referenced in code comments and discussed in the README.
